apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::946156973594:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-t7HKGE13e6vP
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::946156973594:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-09-23T06:07:53Z"
  name: aws-auth
  namespace: kube-system
  uid: 1b38e01b-70f4-44ce-a0f6-bf481c5d662d
